development:
  cas_base_url: 'https://passport-test.kaikeba.com'
  cas_service_url: 'http://0.0.0.0:3000/service'

production:
  cas_base_url: 'https://passport-test.kaikeba.com'
  cas_service_url: 'http://kkb.shooter.gl/service'
